import type { ContentCatalog } from './model';

export const contentCatalog = {
  weapons: [
    {
      id: 'weapon-pulse-cannon',
      name: 'Pulse Cannon',
      origin: 'earth',
      damage: 10,
      shotsPerSecond: 4,
      projectileCount: 1,
      projectileSpeed: 620,
      spread: 0,
      penetration: 'single-target',
      visualProfile: 'machine-gun',
      marketPrice: null,
    },
    {
      id: 'weapon-impulse-accelerator',
      name: 'Impulse Accelerator',
      origin: 'earth',
      damage: 60,
      shotsPerSecond: 1,
      projectileCount: 1,
      projectileSpeed: 760,
      spread: 0,
      penetration: 'all-targets',
      visualProfile: 'impulse-accelerator',
      marketPrice: {
        minimum: 620_000,
        maximum: 680_000,
      },
    },
    {
      id: 'weapon-split-pulse',
      name: 'Split Pulse Emitter',
      origin: 'alien',
      damage: 7.5,
      shotsPerSecond: 6,
      projectileCount: 2,
      projectileSpeed: 620,
      spread: 12,
      penetration: 'single-target',
      visualProfile: 'split-pulse',
      marketPrice: null,
    },
    {
      id: 'weapon-canister-cannon',
      name: 'Canister Aircraft Cannon',
      origin: 'earth',
      damage: 7,
      shotsPerSecond: 1.8,
      projectileCount: 6,
      projectileSpeed: 760,
      spread: 13,
      penetration: 'single-target',
      visualProfile: 'canister-cannon',
      marketPrice: null,
    },
    {
      id: 'weapon-rocket-pod',
      name: 'Rocket Pod',
      origin: 'earth',
      damage: 40,
      shotsPerSecond: 0,
      projectileCount: 1,
      projectileSpeed: 700,
      spread: 0,
      penetration: 'single-target',
      visualProfile: 'rocket-pod',
      marketPrice: {
        minimum: 380_000,
        maximum: 420_000,
      },
    },
  ],
  alienTechnologies: [
    {
      id: 'alien-prism-unclassified',
      codename: 'Unclassified Prism',
      category: 'offence',
      danger: 3,
      reliability: 2,
      signalGlyphs: '△ ◇ ∴',
      preservationResearch: 10,
      passiveEffect: {
        id: 'effect-prismatic-sheath',
        name: 'Prismatic Sheath',
        armourDamageMultiplier: 0.75,
      },
      weaponTransformation: {
        id: 'weapon-split-pulse',
        name: 'Split Pulse Emitter',
        projectileCount: 2,
        damageMultiplier: 0.75,
        spread: 12,
      },
    },
  ],
  pilots: [
    {
      id: 'pilot-kestrel',
      callsign: 'Kestrel',
      speedMultiplier: 1,
      damageMultiplier: 1,
    },
  ],
  enemies: [
    {
      id: 'enemy-scout',
      name: 'Scout',
      armour: 10,
      speed: 150,
      contactDamage: 12,
      score: 100,
      movementPattern: 'straight',
      kind: 'regular',
      materialReward: 1,
      creditReward: 8_000,
      ranged: null,
    },
    {
      id: 'enemy-weaver',
      name: 'Weaver',
      armour: 20,
      speed: 105,
      contactDamage: 18,
      score: 250,
      movementPattern: 'sine',
      kind: 'regular',
      materialReward: 2,
      creditReward: 12_000,
      ranged: null,
    },
    {
      id: 'enemy-warden',
      name: 'Warden',
      armour: 240,
      speed: 92,
      contactDamage: 35,
      score: 2500,
      movementPattern: 'sine',
      kind: 'elite',
      materialReward: 18,
      creditReward: 100_000,
      ranged: {
        shotDamage: 6,
        shotSpeed: 240,
        shotIntervalMs: 1050,
      },
    },
    {
      id: 'enemy-gunship',
      name: 'Gunship',
      armour: 26,
      speed: 70,
      contactDamage: 14,
      score: 320,
      movementPattern: 'straight',
      kind: 'regular',
      materialReward: 2,
      creditReward: 16_000,
      ranged: {
        shotDamage: 8,
        shotSpeed: 280,
        shotIntervalMs: 2400,
      },
    },
  ],
  economy: {
    startingCredits: 500_000,
    missedEnemyPenaltyMultiplier: 5,
  },
  buildings: [
    {
      id: 'building-laboratory',
      creditCost: 300_000,
      materialCost: 10,
      constructionSorties: 1,
      maintenanceCreditCost: 5_000,
      requiredBlueprintId: null,
      requiredBuildingId: null,
    },
    {
      id: 'building-workshop',
      creditCost: 450_000,
      materialCost: 15,
      constructionSorties: 2,
      maintenanceCreditCost: 8_000,
      requiredBlueprintId: null,
      requiredBuildingId: 'building-laboratory',
    },
    {
      id: 'building-quarantine-centre',
      creditCost: 350_000,
      materialCost: 20,
      constructionSorties: 2,
      maintenanceCreditCost: 6_000,
      requiredBlueprintId: 'blueprint-safe-containment',
      requiredBuildingId: 'building-workshop',
    },
    {
      id: 'building-trade-centre',
      creditCost: 350,
      materialCost: 15,
      constructionSorties: 1,
      maintenanceCreditCost: 6,
      requiredBlueprintId: null,
      requiredBuildingId: 'building-workshop',
    },
  ],
  staffRoles: [
    {
      id: 'staff-scientist',
      creditCost: 150_000,
      requiredBuildingId: 'building-laboratory',
      maximumHeadcount: null,
    },
    {
      id: 'staff-engineer',
      creditCost: 180_000,
      requiredBuildingId: 'building-workshop',
      maximumHeadcount: 3,
    },
    {
      id: 'staff-trader',
      creditCost: 200_000,
      requiredBuildingId: 'building-trade-centre',
      maximumHeadcount: 1,
    },
    {
      id: 'staff-manager',
      creditCost: 250_000,
      requiredBuildingId: null,
      maximumHeadcount: 1,
    },
  ],
  blueprints: [
    {
      id: 'blueprint-alien-technology-capturer',
      researchDomain: 'earth',
      requiredProgress: 3,
      researchCreditCost: 120_000,
      requiredBuildingId: 'building-laboratory',
      requiredStaffRoleId: 'staff-scientist',
      outputEquipmentId: 'equipment-alien-technology-capturer',
    },
  ],
  buildingBlueprints: [
    {
      id: 'blueprint-safe-containment',
      researchDomain: 'earth',
      requiredProgress: 3,
      researchCreditCost: 100_000,
      requiredBuildingId: 'building-laboratory',
      requiredStaffRoleId: 'staff-scientist',
      outputBuildingId: 'building-quarantine-centre',
    },
  ],
  adaptedWeaponBlueprints: [
    {
      id: 'blueprint-split-pulse-adaptation',
      researchDomain: 'alien',
      outputWeaponId: 'weapon-split-pulse',
      productionCreditCost: 250_000,
      productionMaterialCost: 8,
      productionSorties: 1,
      requiredProductionBuildingId: 'building-workshop',
      requiredProductionStaffRoleId: 'staff-engineer',
    },
  ],
  researchWeaponBlueprints: [
    {
      id: 'blueprint-canister-cannon',
      researchDomain: 'earth',
      requiredProgress: 3,
      researchCreditCost: 150_000,
      requiredBuildingId: 'building-laboratory',
      requiredStaffRoleId: 'staff-scientist',
      outputWeaponId: 'weapon-canister-cannon',
      productionCreditCost: 200_000,
      productionMaterialCost: 6,
      productionSorties: 1,
      requiredProductionBuildingId: 'building-workshop',
      requiredProductionStaffRoleId: 'staff-engineer',
    },
  ],
  equipment: [
    {
      id: 'equipment-alien-technology-capturer',
      creditCost: 250_000,
      materialCost: 10,
      productionSorties: 1,
      requiredBuildingId: 'building-workshop',
      requiredStaffRoleId: 'staff-engineer',
    },
  ],
  marketWeaponBlueprints: [
    {
      id: 'blueprint-impulse-accelerator-production',
      weaponId: 'weapon-impulse-accelerator',
      minimumSorties: 5,
      marketPrice: {
        minimum: 180_000,
        maximum: 220_000,
      },
      productionCreditCost: 220_000,
      productionMaterialCost: 8,
      productionSorties: 1,
      requiredBuildingId: 'building-workshop',
      requiredStaffRoleId: 'staff-engineer',
    },
  ],
  weaponUpgrades: [
    {
      id: 'upgrade-machine-gun-reinforced-ammunition',
      weaponId: 'weapon-pulse-cannon',
      researchCreditCost: 140,
      productionCreditCost: 90_000,
      productionMaterialCost: 4,
      productionSorties: 1,
      requiredResearchBuildingId: 'building-laboratory',
      requiredStaffRoleId: 'staff-scientist',
      requiredProductionBuildingId: 'building-workshop',
      requiredProductionStaffRoleId: 'staff-engineer',
      requiredBlueprintId: null,
      requiredLocallyProducedWeaponId: null,
      damageMultiplier: 2,
      cadenceMultiplier: 1,
    },
    {
      id: 'upgrade-impulse-accelerator-accumulator',
      weaponId: 'weapon-impulse-accelerator',
      researchCreditCost: 180,
      productionCreditCost: 120_000,
      productionMaterialCost: 6,
      productionSorties: 1,
      requiredResearchBuildingId: 'building-laboratory',
      requiredStaffRoleId: 'staff-scientist',
      requiredProductionBuildingId: 'building-workshop',
      requiredProductionStaffRoleId: 'staff-engineer',
      requiredBlueprintId: 'blueprint-impulse-accelerator-production',
      requiredLocallyProducedWeaponId: 'weapon-impulse-accelerator',
      damageMultiplier: 1,
      cadenceMultiplier: 1.25,
    },
  ],
  aircraft: [
    {
      id: 'aircraft-interceptor',
      name: 'Interceptor',
      role: 'Light interceptor // balanced speed and armour',
      origin: 'earth',
      armour: 100,
      speedMultiplier: 1,
      damageMultiplier: 1,
      refuelCreditCost: 30_000,
      weaponSlotCount: 2,
      supplierCountryId: 'council-ukraine',
      visual: {
        hullColor: 0x9dd7c7,
        accentColor: 0x2f6f63,
        silhouette: [0, -18, 10, 4, 4, 10, -4, 10, -10, 4],
      },
      marketPrice: null,
    },
    {
      id: 'aircraft-gunship',
      name: 'Gunship',
      role: 'Assault gunship // heavier armour, slower, harder hits',
      origin: 'earth',
      armour: 150,
      speedMultiplier: 0.82,
      damageMultiplier: 1.15,
      refuelCreditCost: 45_000,
      weaponSlotCount: 3,
      supplierCountryId: 'council-ukraine',
      visual: {
        hullColor: 0xd7a86b,
        accentColor: 0x7a5a2e,
        silhouette: [0, -14, 14, 0, 18, 6, 12, 12, 14, 20, -14, 20, -12, 12, -18, 6, -14, 0],
      },
      marketPrice: {
        minimum: 900_000,
        maximum: 1_100_000,
      },
    },
    {
      id: 'aircraft-aegis',
      name: 'Aegis',
      role: 'Heavy tank // most armour, slowest, heaviest hits',
      origin: 'earth',
      armour: 210,
      speedMultiplier: 0.68,
      damageMultiplier: 1.3,
      refuelCreditCost: 60_000,
      weaponSlotCount: 4,
      supplierCountryId: 'council-brazil',
      visual: {
        hullColor: 0xa9b7d7,
        accentColor: 0x4c5a78,
        silhouette: [0, -16, 12, -6, 12, 12, 0, 20, -12, 12, -12, -6],
      },
      marketPrice: {
        minimum: 1_300_000,
        maximum: 1_600_000,
      },
    },
    {
      id: 'aircraft-yanlong',
      name: 'Yanlong',
      role: 'PRC-sourced striker // strong economy, four primary slots',
      origin: 'earth',
      armour: 180,
      speedMultiplier: 0.9,
      damageMultiplier: 1.2,
      refuelCreditCost: 50_000,
      weaponSlotCount: 4,
      supplierCountryId: 'council-prc',
      visual: {
        hullColor: 0xe0b36a,
        accentColor: 0x7a2e2e,
        silhouette: [0, -16, 6, -6, 16, -2, 14, 10, 18, 18, -18, 18, -14, 10, -16, -2, -6, -6],
      },
      marketPrice: {
        minimum: 1_000_000,
        maximum: 1_300_000,
      },
    },
  ],
  councilStates: [
    {
      id: 'council-prc',
      nameKey: 'country.prc',
    },
    {
      id: 'council-ukraine',
      nameKey: 'country.ukraine',
    },
    {
      id: 'council-brazil',
      nameKey: 'country.brazil',
    },
    {
      id: 'council-india',
      nameKey: 'country.india',
    },
    {
      id: 'council-usa',
      nameKey: 'country.usa',
    },
    {
      id: 'council-uk',
      nameKey: 'country.uk',
    },
    {
      id: 'council-germany',
      nameKey: 'country.germany',
    },
    {
      id: 'council-japan',
      nameKey: 'country.japan',
    },
    {
      id: 'council-france',
      nameKey: 'country.france',
    },
  ],
  nationGifts: {
    'council-ukraine': { credits: 90_000, materials: 2 },
    'council-prc': { credits: 100_000, materials: 2 },
    'council-usa': { credits: 120_000, materials: 1 },
    'council-uk': { credits: 80_000, materials: 1 },
    'council-germany': { credits: 70_000, materials: 2 },
    'council-japan': { credits: 60_000, materials: 2 },
    'council-france': { credits: 70_000, materials: 1 },
    'council-india': { credits: 50_000, materials: 1 },
    'council-brazil': { credits: 40_000, materials: 1 },
  },
  consumables: [
    {
      id: 'consumable-rockets',
      nameKey: 'content.rocketAmmo',
      creditCost: 40,
      materialCost: 1,
      chargesPerSortie: 3,
      marketPrice: {
        minimum: 30_000,
        maximum: 50_000,
      },
    },
  ],
} as const satisfies ContentCatalog;
