import type { ContentCatalog } from './model';

export const contentCatalog = {
  weapons: [
    {
      id: 'weapon-pulse-cannon',
      name: 'Pulse Cannon',
      origin: 'earth',
      damage: 10,
      shotsPerSecond: 4,
      projectileCount: 1,
      projectileSpeed: 620,
      spread: 0,
      penetration: 'single-target',
      visualProfile: 'machine-gun',
      marketPrice: null,
    },
    {
      id: 'weapon-impulse-accelerator',
      name: 'Impulse Accelerator',
      origin: 'earth',
      damage: 60,
      shotsPerSecond: 1,
      projectileCount: 1,
      projectileSpeed: 760,
      spread: 0,
      penetration: 'all-targets',
      visualProfile: 'impulse-accelerator',
      marketPrice: {
        minimum: 620,
        maximum: 680,
      },
    },
    {
      id: 'weapon-split-pulse',
      name: 'Split Pulse Emitter',
      origin: 'alien',
      damage: 7.5,
      shotsPerSecond: 6,
      projectileCount: 2,
      projectileSpeed: 620,
      spread: 12,
      penetration: 'single-target',
      visualProfile: 'split-pulse',
      marketPrice: null,
    },
  ],
  alienTechnologies: [
    {
      id: 'alien-prism-unclassified',
      codename: 'Unclassified Prism',
      category: 'offence',
      danger: 3,
      reliability: 2,
      signalGlyphs: '△ ◇ ∴',
      preservationResearch: 10,
      passiveEffect: {
        id: 'effect-prismatic-sheath',
        name: 'Prismatic Sheath',
        armourDamageMultiplier: 0.75,
      },
      weaponTransformation: {
        id: 'weapon-split-pulse',
        name: 'Split Pulse Emitter',
        projectileCount: 2,
        damageMultiplier: 0.75,
        spread: 12,
      },
    },
  ],
  pilots: [
    {
      id: 'pilot-kestrel',
      callsign: 'Kestrel',
      speedMultiplier: 1,
      damageMultiplier: 1,
    },
  ],
  enemies: [
    {
      id: 'enemy-scout',
      name: 'Scout',
      armour: 10,
      speed: 150,
      contactDamage: 12,
      score: 100,
      movementPattern: 'straight',
      kind: 'regular',
      materialReward: 1,
      creditReward: 8,
    },
    {
      id: 'enemy-weaver',
      name: 'Weaver',
      armour: 20,
      speed: 105,
      contactDamage: 18,
      score: 250,
      movementPattern: 'sine',
      kind: 'regular',
      materialReward: 2,
      creditReward: 12,
    },
    {
      id: 'enemy-warden',
      name: 'Warden',
      armour: 240,
      speed: 92,
      contactDamage: 35,
      score: 2500,
      movementPattern: 'sine',
      kind: 'elite',
      materialReward: 18,
      creditReward: 100,
    },
  ],
  economy: {
    startingCredits: 500,
    missedEnemyPenaltyMultiplier: 5,
  },
  buildings: [
    {
      id: 'building-laboratory',
      creditCost: 300,
      materialCost: 10,
      requiredBlueprintId: null,
      requiredBuildingId: null,
    },
    {
      id: 'building-workshop',
      creditCost: 450,
      materialCost: 15,
      requiredBlueprintId: null,
      requiredBuildingId: 'building-laboratory',
    },
    {
      id: 'building-quarantine-centre',
      creditCost: 350,
      materialCost: 20,
      requiredBlueprintId: 'blueprint-safe-containment',
      requiredBuildingId: 'building-workshop',
    },
  ],
  staffRoles: [
    {
      id: 'staff-scientist',
      creditCost: 150,
      requiredBuildingId: 'building-laboratory',
      maximumHeadcount: null,
    },
    {
      id: 'staff-engineer',
      creditCost: 180,
      requiredBuildingId: 'building-workshop',
      maximumHeadcount: 1,
    },
  ],
  blueprints: [
    {
      id: 'blueprint-alien-technology-capturer',
      researchDomain: 'earth',
      requiredProgress: 3,
      requiredBuildingId: 'building-laboratory',
      requiredStaffRoleId: 'staff-scientist',
      outputEquipmentId: 'equipment-alien-technology-capturer',
    },
  ],
  buildingBlueprints: [
    {
      id: 'blueprint-safe-containment',
      researchDomain: 'earth',
      requiredProgress: 3,
      requiredBuildingId: 'building-laboratory',
      requiredStaffRoleId: 'staff-scientist',
      outputBuildingId: 'building-quarantine-centre',
    },
  ],
  adaptedWeaponBlueprints: [
    {
      id: 'blueprint-split-pulse-adaptation',
      researchDomain: 'alien',
      outputWeaponId: 'weapon-split-pulse',
      productionCreditCost: 250,
      productionMaterialCost: 8,
      requiredProductionBuildingId: 'building-workshop',
      requiredProductionStaffRoleId: 'staff-engineer',
    },
  ],
  equipment: [
    {
      id: 'equipment-alien-technology-capturer',
      creditCost: 250,
      materialCost: 10,
      requiredBuildingId: 'building-workshop',
      requiredStaffRoleId: 'staff-engineer',
    },
  ],
  marketWeaponBlueprints: [
    {
      id: 'blueprint-impulse-accelerator-production',
      weaponId: 'weapon-impulse-accelerator',
      minimumSorties: 5,
      marketPrice: {
        minimum: 180,
        maximum: 220,
      },
      productionCreditCost: 220,
      productionMaterialCost: 8,
      requiredBuildingId: 'building-workshop',
      requiredStaffRoleId: 'staff-engineer',
    },
  ],
  weaponUpgrades: [
    {
      id: 'upgrade-machine-gun-reinforced-ammunition',
      weaponId: 'weapon-pulse-cannon',
      researchCreditCost: 140,
      productionCreditCost: 90,
      productionMaterialCost: 4,
      requiredResearchBuildingId: 'building-laboratory',
      requiredStaffRoleId: 'staff-scientist',
      requiredProductionBuildingId: 'building-workshop',
      requiredProductionStaffRoleId: 'staff-engineer',
      requiredBlueprintId: null,
      requiredLocallyProducedWeaponId: null,
      damageMultiplier: 2,
      cadenceMultiplier: 1,
    },
    {
      id: 'upgrade-impulse-accelerator-accumulator',
      weaponId: 'weapon-impulse-accelerator',
      researchCreditCost: 180,
      productionCreditCost: 120,
      productionMaterialCost: 6,
      requiredResearchBuildingId: 'building-laboratory',
      requiredStaffRoleId: 'staff-scientist',
      requiredProductionBuildingId: 'building-workshop',
      requiredProductionStaffRoleId: 'staff-engineer',
      requiredBlueprintId: 'blueprint-impulse-accelerator-production',
      requiredLocallyProducedWeaponId: 'weapon-impulse-accelerator',
      damageMultiplier: 1,
      cadenceMultiplier: 1.25,
    },
  ],
} as const satisfies ContentCatalog;
